@Lms_backend_Api_HostAddress = http://localhost:5217
@moduleId = 1
@id = 1
@resourceId = 1
@userid = 1

//ActivitiesController
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{{moduleId}}}/activities/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{{moduleId}}}/activities/{{id}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/{{{moduleId}}}/activities/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/{{resourceId}}/


###
DELETE {{Lms_backend_Api_HostAddress}}/api/modules/{{moduleId}}/activities/{{id}}/resources/{{resourceId}}/
Accept: application/json

###

//ModulesController
GET {{Lms_backend_Api_HostAddress}}/api/modules/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/modules/{{id}}/resources/{{resourceId}}/
Accept: application/json

###

//ResourcesController
GET {{Lms_backend_Api_HostAddress}}/api/resources/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/resources/{{id}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/resources/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/resources/{{id}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/resources/{{id}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/resources/{{id}}/
Accept: application/json

###

//CoursesController
GET {{Lms_backend_Api_HostAddress}}/api/courses/my-courses/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/courses/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/courses/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
PATCH {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/{{resourceId}}/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/courses/{{id}}/resources/{{resourceId}}/
Accept: application/json

###

//AdminController
POST {{Lms_backend_Api_HostAddress}}/api/admin/Register/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/admin/getusers/
Accept: application/json

###
DELETE {{Lms_backend_Api_HostAddress}}/api/admin/deleteuser/{{userId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/disableuser/{{userId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/enableuser/{{userId}}/
Accept: application/json

###
GET {{Lms_backend_Api_HostAddress}}/api/admin/getuserstats/{{userId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/updateuser/{{userId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/resetpassword/{{userId}}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/addcoursetouser/{{userId}}/{courseid}/
Accept: application/json

###
PUT {{Lms_backend_Api_HostAddress}}/api/admin/removecoursefromuser/{{userId}}/{courseid}/
Accept: application/json

###

//AuthController
POST {{Lms_backend_Api_HostAddress}}/api/auth/login/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/auth/token/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/auth/logout/
Accept: application/json

###
POST {{Lms_backend_Api_HostAddress}}/api/auth/register/
Accept: application/json

###