// <auto-generated />
using System;
using Lms_backend.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lms_backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904090939_AddingIdentityCore")]
    partial class AddingIdentityCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lms_backend.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartTimeOffset")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Activities", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000001"),
                            ActivityType = 0,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Overview of version control concepts and setting up your first Git repository.",
                            DurationMinutes = 60,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Introduction to Git",
                            StartTimeOffset = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000002"),
                            ActivityType = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands-on practice creating branches, merging changes, and resolving conflicts.",
                            DurationMinutes = 90,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Git Branching Exercise",
                            StartTimeOffset = 60,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000003"),
                            ActivityType = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Self-paced reading covering Git basics, branching, and the Git workflow.",
                            DurationMinutes = 120,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "Read Pro Git Book (Ch. 1-3)",
                            StartTimeOffset = 30,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000004"),
                            ActivityType = 0,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Variables, data types, operators, and control flow in C#.",
                            DurationMinutes = 90,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "C# Syntax & Types",
                            StartTimeOffset = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000005"),
                            ActivityType = 0,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classes, objects, inheritance, interfaces, and encapsulation.",
                            DurationMinutes = 90,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "Object-Oriented Programming in C#",
                            StartTimeOffset = 90,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000006"),
                            ActivityType = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Practice designing classes and interfaces for a small console application.",
                            DurationMinutes = 120,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "OOP Practice Exercise",
                            StartTimeOffset = 60,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000007"),
                            ActivityType = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Build a small console application applying the OOP principles covered in this module.",
                            DurationMinutes = 180,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "Console App Assignment",
                            StartTimeOffset = 180,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000008"),
                            ActivityType = 0,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Images, containers, volumes, and networking basics with Docker.",
                            DurationMinutes = 60,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000006"),
                            Name = "Docker Fundamentals",
                            StartTimeOffset = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("66666666-0000-0000-0000-000000000009"),
                            ActivityType = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Group review and feedback on Dockerfiles written for the sample project.",
                            DurationMinutes = 45,
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000006"),
                            Name = "Dockerfile Review Session",
                            StartTimeOffset = 45,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "identity");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "268d2cf5-1946-4e8e-b915-7f66ea6abed8",
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            GivenName = "Alex",
                            LastName = "Nilsson",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "01f429a1-8204-4597-bc2a-e763ee8e1e9b",
                            CourseId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            GivenName = "Maria",
                            LastName = "Svensson",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000003"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48fd668d-3a3b-40d5-9c9e-e96de93a4458",
                            CourseId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            GivenName = "Johan",
                            LastName = "Berg",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-0000-0000-0000-000000000004"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a08b3ba-e848-4ca6-aee6-51fa69ded960",
                            CourseId = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmailConfirmed = false,
                            GivenName = "Sara",
                            LastName = "Lindqvist",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Courses", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn to build modern web applications end-to-end, from responsive front-ends to REST APIs and databases.",
                            Duration = 12,
                            Name = "Full-Stack Web Development",
                            StartDate = new DateOnly(2026, 2, 2),
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep dive into C#, object-oriented design, and building robust web APIs with ASP.NET Core and EF Core.",
                            Duration = 10,
                            Name = "Backend Development with C# & .NET",
                            StartDate = new DateOnly(2026, 2, 2),
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Containerize, automate, and deploy applications using Docker, CI/CD pipelines, and cloud platforms.",
                            Duration = 8,
                            Name = "Cloud & DevOps Engineering",
                            StartDate = new DateOnly(2026, 3, 2),
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.ActivityResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ActivityId", "ResourceId")
                        .IsUnique();

                    b.ToTable("ActivityResources", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000001"),
                            ActivityId = new Guid("66666666-0000-0000-0000-000000000001"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000002"),
                            ActivityId = new Guid("66666666-0000-0000-0000-000000000002"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000003"),
                            ActivityId = new Guid("66666666-0000-0000-0000-000000000006"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("99999999-0000-0000-0000-000000000004"),
                            ActivityId = new Guid("66666666-0000-0000-0000-000000000007"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.CourseModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("StartTimeOffset")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("CourseId", "ModuleId")
                        .IsUnique();

                    b.ToTable("CourseModules", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StartTimeOffset = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000002"),
                            StartTimeOffset = 7
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000003"),
                            StartTimeOffset = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            StartTimeOffset = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            StartTimeOffset = 7
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000006"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000005"),
                            StartTimeOffset = 28
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000007"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000003"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000006"),
                            StartTimeOffset = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000008"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000003"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000007"),
                            StartTimeOffset = 14
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.CourseResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("CourseId", "ResourceId")
                        .IsUnique();

                    b.ToTable("CourseResources", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-0000-0000-0000-000000000001"),
                            CourseId = new Guid("11111111-0000-0000-0000-000000000001"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.ModuleResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ModuleId", "ResourceId")
                        .IsUnique();

                    b.ToTable("ModuleResources", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000001"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000001"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000002"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000002"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000003"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000004"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000004"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000005"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("88888888-0000-0000-0000-000000000005"),
                            ModuleId = new Guid("22222222-0000-0000-0000-000000000006"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.UserResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("UserId", "ResourceId")
                        .IsUnique();

                    b.ToTable("UserResource", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            ResourceId = new Guid("55555555-0000-0000-0000-000000000009"),
                            UserId = new Guid("44444444-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Modules", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Version control fundamentals: repositories, commits, branching, merging, and collaborative workflows.",
                            Duration = 1,
                            Name = "Git & Version Control",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Core building blocks of the web: semantic HTML, CSS layout & styling, and JavaScript basics.",
                            Duration = 3,
                            Name = "Frontend Fundamentals",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Building interactive user interfaces with components, props, state, and hooks in React.",
                            Duration = 3,
                            Name = "React Fundamentals",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Core C# syntax, types, control flow, and object-oriented programming concepts.",
                            Duration = 3,
                            Name = "C# Language Fundamentals",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Building REST APIs with ASP.NET Core and persisting data with Entity Framework Core.",
                            Duration = 4,
                            Name = "ASP.NET Core & EF Core",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Packaging and running applications in containers using Docker images and Compose.",
                            Duration = 2,
                            Name = "Containers with Docker",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Automating build, test, and deployment pipelines and deploying to cloud platforms.",
                            Duration = 3,
                            Name = "CI/CD & Cloud Deployment",
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Data")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("ResourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Resources", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "https://git-scm.com/book/en/v2",
                            Description = "Free online book covering everything from Git basics to advanced workflows.",
                            Name = "Pro Git Book",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 1,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "git init | git add . | git commit -m \"msg\" | git branch <name> | git checkout <name> | git merge <name> | git status | git log",
                            Description = "Quick reference for common Git commands.",
                            Name = "Git Cheat Sheet",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
                            Description = "Comprehensive reference and guides for HTML, CSS, and JavaScript.",
                            Name = "MDN Web Docs - JavaScript",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 1,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "Use PascalCase for classes/methods, camelCase for locals/params, prefix interfaces with 'I', keep methods short and single-purpose.",
                            Description = "Notes on naming, formatting, and style conventions used in this course.",
                            Name = "C# Coding Conventions",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "https://learn.microsoft.com/aspnet/core",
                            Description = "Official Microsoft documentation and tutorials for ASP.NET Core.",
                            Name = "Microsoft Learn - ASP.NET Core",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 1,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "https://docs.docker.com/",
                            Description = "Official documentation for Docker Engine, images, and Compose.",
                            Name = "Docker Official Docs",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 1,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "1. Define an interface IShape with an Area() method. 2. Implement Circle and Rectangle. 3. Compute the total area of a list of shapes.",
                            Description = "Step-by-step instructions for the object-oriented programming exercise.",
                            Name = "OOP Practice Instructions",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "Week 1: Git. Weeks 2-4: Frontend Fundamentals. Weeks 5-8: React. Weeks 9-12: Capstone project.",
                            Description = "Full syllabus and schedule for the Full-Stack Web Development course.",
                            Name = "Course Syllabus",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000001"),
                            ResourceType = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "Remember: commit early and often. Use feature branches. Run 'git status' before every commit. Ask Alex about rebase vs merge.",
                            Description = "Personal notes from the Git & Version Control module.",
                            Name = "My Git Notes",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000002"),
                            ResourceType = 0,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Data = "https://github.com/johan-berg/console-app-assignment",
                            Description = "Johan Berg's submitted solution for the console application assignment.",
                            Name = "Console App Assignment Submission",
                            OwnerId = new Guid("44444444-0000-0000-0000-000000000003"),
                            ResourceType = 2,
                            UpdatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Module", "Modules")
                        .WithMany("Activities")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Course", "Course")
                        .WithMany("Users")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.ActivityResource", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Activity", "Activity")
                        .WithMany("Resources")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.CourseModule", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.Module", "Module")
                        .WithMany("Courses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.CourseResource", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Course", "Course")
                        .WithMany("Resources")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.ModuleResource", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Module", "Module")
                        .WithMany("Resources")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Joins.UserResource", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Lms_backend.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Course", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lms_backend.Domain.Entities.Module", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Courses");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
